### PR TITLE
Add setLimits to forward and inverse kinematics

### PR DESCRIPTION
**Pull request by Levi-Armstrong**
This adds the setLimits and I am currently reviewing the update() functions for the individual kinematics. Should finish the review tonight.

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@mpowelson I went through the updates and made a minor changes. Also as going through things I switched it such that change joint limits only pertained to the joint limits and did not include velocity and acceleration. I was not sure if we should go down to this level of granularity or not. I figured we could add other commands for changing velocity and acceleration and then one for all of them ChangeKinematicLimits.

**Comment by Levi-Armstrong** [comment]
Also should we change ChangeJointLimits to ChangeJointJointLimits to align with ChangeJointVelocityLimits and ChangeJointAccelerationLimits?

**Comment by mpowelson** [comment]
@Levi-Armstrong I don't think it really matters. Its another command to add to the command message, but I suppose it does save the user from having to get this limits, modify them, and submit the new limits. With this they could just submit whatever they want to change.

**Comment by mpowelson** [comment]
Let me know when you want me to merge this in.

**Comment by Levi-Armstrong** [comment]
Sounds good I will clean a few things up tonight on my changes and let you know when it is ready.

**Comment by Levi-Armstrong** [comment]
I broke out the limits into there own commands so it is easier on the user to change what they want. Also updated the tesseract_ros PR. The remaining thing is to look at the serialization of the manipulator manager that you highlighted. I am not sure where this should go but should be able to figure out something tonight.

**Comment by Levi-Armstrong** [comment]
@mpowelson Well this is more involved that I expected, but I believe it sets the ground work for the Manipulator Manager. I think with a few more commands we can capture everything. Let me know what you think.

- Remaining Manipulator Command
  - RemoveManipulatorGroup
  - RemoveGroupTCP
  - RemoveGroupState
  - SetGroupDefaultFwdKinSolver
  - SetGroupDefaultInvKinSolver

**Comment by mpowelson** [comment]
@Levi-Armstrong I just squashed the commits. You can rebase now.

**Comment by Levi-Armstrong** [comment]
replaced by PR #8

**Pull request closed without merging**
